###
GET  http://localhost:1234/elements
         
###     
POST http://localhost:1234/elements
Content-Type: application/json
 
{
    "Category": {
      "id": 3,
      "Priority": 1,
      "CategoryName": "Propulsion"
    },
    "name": "Papaassaxxu ssxsaxasde papus papu",
    "weight": 2000,
    "description": "xassa"
} 
    
###   
PATCH http://localhost:1234/elements/467f8425-d656-4f3a-bad3-eee6f79a026b
Content-Type: application/json

{
    "Category": {
      "id": 2,
      "Priority": 1,
      "CategoryName": "Propulsion"
    },
    "name": "Waaacsaxxashi wa",
    "weight": 243000,
    "description": "Para papus con papus"
}


###
DELETE http://localhost:1234/elements/2cb38035-3159-4389-88c5-31564723e924

### POSGRES

