###
GET  http://localhost:1234/elements
         
###     
POST http://localhost:1234/elements
Content-Type: application/json
 
{
    "Category": {
      "id": 3,
      "Priority": 1,
      "CategoryName": "Propulsion"
    },
    "name": "Papu xsaxasde papus papu",
    "weight": 2000,
    "description": "xassa"
}
 
###   
PATCH http://localhost:1234/elements/12ebbfdb-df2f-11ee-9b13-0250fe5d1b54
Content-Type: application/json

{
    "Category": {
      "id": 19,
      "Priority": 1,
      "CategoryName": "Propulsion"
    },
    "name": "Wacsaxxashi wa",
    "weight": 2000,
    "description": "Para papus con papus"
}


###
DELETE http://localhost:1234/elements/714e7798-df1b-11ee-9b13-0250fe5d1b54

