###
GET  http://localhost:1234/categories
        
###     
POST http://localhost:1234/categories
Content-Type: application/json

{
  "Priority": 4,
  "CategoryName": "Ricxassardo MIlos"
}
  
###
PATCH http://localhost:1234/categories/19
Content-Type: application/json

{
  "Priority": 1,
  "CategoryName": "Tienes que hornear unos momazos"
}


###  
DELETE http://localhost:1234/categories/17

