version: "3.9"

services:
  mysqlversion:
    image: mysql:8.3.0
    env_file: ./.env
    ports:
      - "${MYSQLLPORT}:3306"
    volumes:
      - ./BaseSql.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=elementsmars

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysqlversion
    links:
      - mysqlversion
